version: '3.7'
services:
    rpicomponents:
        build: 
            context: '.'
            args:
                - BUILD_TEST=ON
        privileged: true
        volumes: 
            - '/dev/ttyAMA0:/dev/ttyAMA0'
            - '/dev/mem:/dev/mem'